# Generated by Django 4.0.4 on 2022-05-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory_name', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=200)),
                ('JoinedAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_catagory', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('CatId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SiteApp.catagories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=60)),
                ('Item_image', models.FileField(upload_to='media/products/')),
                ('Total_price', models.IntegerField()),
                ('descount_price', models.IntegerField()),
                ('Qty', models.IntegerField()),
                ('Color', models.CharField(default='Red', max_length=10)),
                ('Description', models.CharField(max_length=200)),
                ('Created_At', models.DateField(auto_now=True)),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SiteApp.catagories')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('tracing_number', models.CharField(max_length=150, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('cumpany_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=500)),
                ('appartment', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('payment', models.CharField(default=1, max_length=10)),
                ('Zip_code', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('created_At', models.DateField(auto_now=True)),
                ('tracing_number', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.user_data')),
            ],
        ),
        migrations.CreateModel(
            name='Add_to_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.CharField(default=1, max_length=15)),
                ('Qty', models.IntegerField()),
                ('AddedAt', models.DateField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteApp.user_data')),
            ],
        ),
    ]
